export const CREATE_SESSION = 'CREATE_SESSION';
export const SET_SESSION_VALID = 'SET_SESSION_VALID';
export const SET_CONNECTION = 'SET_CONNECTION';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const START_SESSION = 'START_SESSION';
