export const REGITSER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const AUTH_REQUEST_FAILURE = 'AUTH_REQUEST_FAILURE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const CREATE_SESSION = 'CREATE_SESSION';
export const SET_SESSION_VALID = 'SET_SESSION_VALID';
export const SET_CONNECTION = 'SET_CONNECTION';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const START_SESSION = 'START_SESSION';
